### PR TITLE
Use ros3djs 1.0.0

### PR DESCRIPTION
**Pull request by mvollrath**
ros3djs 1.0.0 is not released yet, but this prepares for the change.

* Upgrade model loaders to r89.
* Remove crufty THREE sources from this repo.
* Remove deprecated ColladaLoader2.

### CODE REVIEW

**Comment by mvollrath** [comment]
ros3djs 1.0.0 is released and this is ready for review.

**Review by jubeira — COMMENTED** [review]
When I run `bower install` I get the following message:
```
Unable to find a suitable version for eventemitter2, please choose one by typing one of the numbers below:
    1) eventemitter2#0.4.14 which resolved to 0.4.14 and is required by roslib#0.18.0
    2) eventemitter2#^4.1.0 which resolved to 4.1.0 and is required by ros3djs#1.0.0, roslibjs#1.0.0
```

Before testing I think we need to sync this branch with master to point to OSRF repositories and also merge this one to align `roslibjs` versions: https://github.com/osrf/polymer-ros-websocket/pull/1/files (the current `ros-websocket` still uses `roslib#0.18.0`).

**Comment by jubeira** [comment]
Alright, I still see the compatibility issue between the new collada loader and `pr2` model described here: https://github.com/osrf/polymer-ros-rviz/issues/14#issuecomment-450661198; it seems a problem with that mesh in particular though -I tried with turtlebot and it works as before-.

I'll run some more tests tomorrow.

**Comment by jubeira** [comment]
One more update: I tested the components and this is looking good:
- [x] Point clouds
- [x] Depth clouds
- [x] Interactive markers
- [x] Markers
- [x] Images
- [x] tf
- [x] Occupancy grid

I'll do a final review tomorrow just in case.

**Review by jubeira — APPROVED** [review]
LGTM!

Some pictures testing 3D functionality:
- UR10 with tf frames and a pointcloud coming from a rosbag:
screenshot from 2019-02-22 10-41-00
- Turtlebot in Gazebo with depth cloud:
screenshot from 2019-02-22 10-35-25

**Pull request merged**
